DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS logs

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  directions TEXT[]
);

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  recipeId INTEGER NOT NULL,
  dateOfEvent TEXT NOT NULL,
  notes TEXT NOT NULL,
  rating INTEGER
);
